---
title: "Angewandte Zeitreihenanalyse mit R - Beispiele"
subtitle: "Schlittgen, Rainer - De Gruyter, 2015 ISBN 978-3-11-041398-4"
author: "Wolfgang Vollmer"
date: '`r Sys.Date()`'
output:
  pdf_document:
    fig_caption: no
    fig_height: 6
    fig_width: 12
    number_sections: yes
    toc: yes
  html_document: default
  word_document:
    toc: yes
  odt_document:
urlcolor: blue
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r initialization, echo = FALSE, message = FALSE, warning = FALSE}
######  variables clean up, library() and	source() statements
setwd("D:/Wolfgang/Programs-R/R-TimeSeriesAnalysis")
rm(list=ls()) # deletes all existing objects / variables !!

library(zoo)
library(tseries) # Finance data can be easily queried using the get.hist.quote
library(stlplus) # Enhanced Seasonal Decomposition of Time Series by Loess
library(tidyverse)
library(magrittr)
library(tsibble)
library(lubridate)  # for year(date) function
# for package overview see:
#                   https://cran.r-project.org/web/views/TimeSeries.html
#                   https://slides.earo.me/rstudioconf19/#16
library(DT)     # R interface to the JavaScript library DataTables
library(fable)
# vignette("fable")
library(gridExtra)

# packages to be considered:
# library(forecast)
# library(xts)

#################################
# library(devtools)
# # devtools::load_all("animals4") # loads package incl. data files (if available)
# 
# devtools::install("D:/Wolfgang/Programs-R/statistikv8")
# devtools::load_all("D:/Wolfgang/Programs-R/statistikv8")
#                             # loads package incl. data files (if available)
# library("statistikv8")
# help("abb14_loess")
# dir("D:/Wolfgang/Programs-R/statistikv8/R/", full.names = TRUE)
#################################

source("ggts_TimeSeries.R")
source("./Data_Schlittgen/tsutil.R")

```

```{r Beispiele Running 2.1 bis 2.34, echo = TRUE}
# Beispiel 2.1 

   y <- scan("./Data_Schlittgen/regen.dat")
   y <- ts(y,start=1878,frequency=1) 
   plot(y)
   plot(y,type="p")
   plot(y,type="o") 
   
   # Beispiel 2.2 

   y <- scan("./Data_Schlittgen/maunaloa.dat")
   y <- y[-c(1:84)]
   y <- ts(y,start=c(1965,1),frequency=12) 
   source("./Data_Schlittgen/tsutil.r")
   a <- aspectratio(y) 
   # windows(width=8*a, height=8)
   ts.plot(y,ylab="CO2",xlab="")
   # windows(width=8*a, height=8*a)
   # ts.plot(y,ylab="CO2",xlab="")  
   
# Beispiel 2.10 

   y <- scan("./Data_Schlittgen/regen.dat") 
   mean(y)
   var(y)
   source("./Data_Schlittgen/tsutil.r")
   out <- statcheck(y,3)
   a<- acf(y,lag.max=15,lwd=3,plot=F)
   plot(0:15,a$acf,type="l",lwd=2,xlab="Lag",ylab="ACF")
   lines(0:15,out$ac[,2],lty=2)
   lines(0:15,out$ac[,3],lty=2)
   lines(0:15,out$ac[,4],lty=2)
   lines(c(0,15),c(0,0)) 
   
   
# Beispiel 2.11 

   y <- scan("./Data_Schlittgen/luchs.dat") 
   y <- ts(log10(y),start=1821,frequency=1)
   plot(y)
   source("./Data_Schlittgen/tsutil.r")
   statcheck(y,3) 
   acf(y,lag.max=25,ci=0)
  
# Beispiel 2.14 ########## läuft nicht, da data file nicht existiert

   # dat <- read.csv("./Data_Schlittgen/prospectValues.csv",header=TRUE,sep=";",dec=",")
   # attach(dat)
   # y <- SyntheticPut - Cash
   # library(np)        
   # b <-  b.star(y)          
   # b<-ceiling(b[2])
   # Boot <- 1000              
   # alpha <- 0.1             
   # n <- length(y)
   # theta <- mean(y) 
   # k <- n%/%b                
   # yb <- rep(0,b*k)  
   # Index <- c(1:(n+1-b))  
   # tstar <- rep(0,Boot)  
   # bo <- 1
   # while (bo <= Boot){                      
   #   a <- sample(Index,k,replace=TRUE)      
   #   for (i in c(1:k)){ yb[(i-1)*b+c(1:b)] <- y[c(a[i]:(a[i]+b-1))] } 
   #   tstar[bo] <- mean(yb)                    
   #   bo<- bo+1  }  
   # v <- var(tstar) 
   # z <- qnorm(1-alpha/2)
   # KI <- c(theta-z*sqrt(v),theta+z*sqrt(v)) 
   # print(KI) 

# Beispiel 2.16 

   y <- scan("./Data_Schlittgen/herzschlag.dat")
   n <- length(y)
   t <- c(1:n)
   t2 <- t^2; t3 <- t^3; t4 <- t^4
   out <- lm(y ~ t + t2 + t3 + t4)
   ts.plot(y,xlab="Zeit",ylab="Herzschlag") 
   lines(t,out$fitted.values) 

# Beispiel 2.17 

   anova(out) 
   summary(out) 

# Beispiel 2.18   Fortsetzung Beispiel 2.16 Herzschlag 

  library(leaps)
  l1 <- leaps(x= as.matrix(cbind(t,t2,t3,t4)),y=y,method="Cp")
  l2 <- leaps(x= as.matrix(cbind(t,t2,t3,t4)),y=y,method="r2") 
  cbind(l1$which,l1$Cp,l2$r2) 
      

# Beispiel 2.19    

   qqnorm(out$residuals) 
   abline(mean(out$residuals),sd(out$residuals)) 
   Regen <- scan("./Data_Schlittgen/regen.dat")
   qqnorm(Regen) 
   abline(mean(Regen),sd(Regen))

# Beispiel 2.20    

   library(car)
   durbinWatsonTest(out)
  



# Beispiel 2.21    

   dat<- read.table("./Data_Schlittgen/usapop.dat", header=T)
   attach(dat)
   n <- length(Pop)
   Pop <- Pop/1000
   Jahr <- c(1:n) 
   r <- (Pop[-1]-Pop[-n])/Pop[-1]
   out1 <- lm(r~Pop[-n])  
   theta3 <- out1$coefficients[1]
   eta <- (-1)*out1$coefficients[1]/out1$coefficients[2]
   theta2 <- mean(Pop*exp(-theta3*c(1:n))/(eta-Pop))
   theta1 <- eta*theta2
   start <- c(theta1,theta2,theta3) 
   f <- function(par) sum((Pop-par[1]/(par[2]+exp(-par[3]*c(1:n))))^2)
   out3 <- optim(start,f)
   theta <- out3$par
   fu <- function(x)  theta[1]/(theta[2] + exp(-theta[3]*x))
   ts.plot(Pop,xlab="Zeit",ylab="USAPOP")
   curve(fu,add=T,lty=2) 

# Beispiel 2.22

   Unfall <- scan("./Data_Schlittgen/unfall.dat")
   y <- ts(Unfall,start=c(1974,1),frequency=12)
   source("./Data_Schlittgen/tsutil.r") 
   glatt <- runmean(y,24)
   plot(y)    
   lines(glatt) 

# Beispiel 2.23    

   AE <- scan("./Data_Schlittgen/auftragseingang.dat")
   y <- ts(AE,start=c(1968,1),frequency=12)
   source("./Data_Schlittgen/tsutil.r") 
   g <- smoothls(y^0.25,100)    
   plot(y^0.25,)
   lines(seq(1968,1968+(length(y)-1)/12,1/12), g)

# Beispiel 2.24    

   steuern <- scan("./Data_Schlittgen/steuern.dat")
   y <- ts(steuern,start= c(1994,1),frequency=12) 
   source("./Data_Schlittgen/tsutil.r") 
   simpledecomp(y,trend=2,saison=12)  

# Beispiel 2.25    

   dat <- read.table("./Data_Schlittgen/prodindex.dat",header=TRUE)
   y <- rev(dat[,3])
   x <- ts(y,start=c(2000,1),frequency=12) 
   source("./Data_Schlittgen/tsutil.r")
   gs <- splinedecomp(x,12,20,5,Plot=TRUE)

# Beispiel 2.26    

   monthplot(gs[,2],type="h")

# Beispiel 2.27    

   AE <- scan("./Data_Schlittgen/auftragseingang.dat")
   y <- ts(AE,start=c(1968,1),frequency=12)
   plot(y) 
   source("./Data_Schlittgen/tsutil.r")
   l <- BoxCox(y,9)

# Beispiel 2.28    

   y <- scan("./Data_Schlittgen/luchs.dat")  
   source("./Data_Schlittgen/tsutil.r")
   symplot(y)
   symplot(log10(y)) 

# Beispiel 2.31    

   y <- scan("./Data_Schlittgen/maunaloa.dat")   
   y <- y[-c(1:84)]
   source("./Data_Schlittgen/tsutil.r")
   vartable(y,12)

# Beispiel 2.32    

   jlast <- scan("./Data_Schlittgen/jlast.dat")
   n <- length(jlast) 
   t1 <- c(1:25) 
   y <- jlast[1:25]
   out <- lm(y~t1)
   new <- data.frame(t1=c(26:37))
   out1 <- predict(out,new,interval="prediction")
   plot(c(1:n),jlast,type="l",ylim=c(min(y),max(out1[,3])))  
   lines(new$t1,out1[,1],lty=2) 
   lines(new$t1,out1[,2],lty=3) 
   lines(new$t1,out1[,3],lty=3) 

# Beispiel 2.33    

   y <- scan("./Data_Schlittgen/hsv.dat")
   y <- ts(y,start=1964)
   out <- HoltWinters(y,alpha=NULL,beta=FALSE,gamma=FALSE)  
   p <- predict(out, n.ahead=4)
   plot(out,p)   

# Beispiel 2.34    

   y <- scan("./Data_Schlittgen/auftrag.dat")
   y <- ts(y,start=c(1972,1),frequency=12)
   out <- HoltWinters(y) 
   p <- predict(out, n.ahead=12)
   plot(out,p)     
   
```

```{r Plot Zeitreiehe }
library(aTSA)     # for stationary.test(data_ts) and adf.test(data_ts) - same
library(fractal)  # for stationaryty()
library(LaplacesDemon)

city <- "Basel"
weather_data_wide <- 
  readRDS(paste0("../R-WeatherAnalysis/WeatherData_", city, ".rds")) %>% 
  filter(Temp_Precip == "Temperature") %>% 
  dplyr::select(Year, Jan:Dec)

CO2_data_wide <- readRDS("./Data_MaunaLoa_CO2/CO2_MaunaLoa.rds")

data_wide <- CO2_data_wide
data_long <- data_wide %>%
  pivot_longer(cols = Jan:Dec,
               names_to = c("Month"),
               values_to = "count")

start_year <- 2001
start_month <- 1
end_year <- 2019
end_month <- 12
freq <- 12

# filtering in same range important, ts() does not look for any time values
data_long %<>% filter(Year >= start_year & Year <= end_year)
  
data_ts <- ts(data_long$count, start= c(start_year, start_month), 
              end=c(end_year, end_month), frequency = freq)
plot(data_ts)

data <- data_long %>%  
  unite("Year_Month", Year, Month, sep = "-", remove = TRUE) %>% 
  mutate(Year_Month = yearmonth(Year_Month))

ggplot_w_rol_mean(data, "Year_Month", "count", span = 36)

```

## Stationary Process Test

Strict-sense stationarity / Weak (wide-sense) stationarity

Trend Stationary - underlying trend (function solely of time) can be removed, 
leaving a stationary process

```{r}
## Stationarity Test

stationary.test(data_ts)
adf.test(data_ts)

statio <-
  stationarity(data_long$count, n.taper = 6,
               n.block = max(c(12, floor(logb(length(data_ts), base = 12)))),
               significance = 0.05, center = TRUE, recenter = FALSE)
summary(statio)

is.stationary(data_long$count)
# statcheck() # maybe from Schlittgen
statcheck(data_long$count, 6)
acf(data_long$count,lag.max=15)
# plot(0:15,a$acf,type="l",lwd=2,xlab="Lag",ylab="ACF") # length(a$acf)-1 (lag.max =15)
# lines(0:18,out$ac[,2],lty=2) # nrow(out$ac) -1 
# lines(0:18,out$ac[,3],lty=2)
# lines(0:18,out$ac[,4],lty=2)
# lines(c(0,18),c(0,0)) 

```

## Peridicities - Season Frequency  

### Correlogram - autocovariance / autocorrelation function

```{r}
# Korrelogramm
# „empirische Autokovarianz- und Autokorrelationsfunktion (ACF)
# 
#  Lag - Verschiebung, des betrachteten Zeitfensters
#  Lag 0: Jan mit Jan (sich selbst)
#  Lag 1: Jan mit Feb (next Feb , einen Monat weiter)
#  
#  Lag 12: Jan mit Jan (des nächsten Jahres)
#  t <- c(1,2,3) => lag(t): [1] NA  1  2
data_acf <- acf(data_ts, lag.max = 24) # type = "correlation" (the default)
# plot(data_acf)

# Temperaturzeitreihe weist natürliche saisonale Schwankungen auf
# => gut im Korellogramm zu erkennen kann
# Der Januar wird als Basis gewählt und die Monate um den Januar herum weisen 
#   eine sehr hohe positive Korrelation auf
# die Sommermonate in der Mitte (0,5) des Jahres weisen eine starke
#                  negative Korrelation auf
data_acf_tbl <- as_tibble(data_acf$acf) %>% 
  mutate(ACF = as.vector(V1),
         Lag = as.vector(data_acf$lag))
ggplot(data_acf_tbl, aes(Lag, ACF)) +
  geom_bar(stat = "identity", width = 0.01) +
    ggtitle( paste("Time Series Correlogram - Type ", data_acf$type))

```

### Periodogram - Estimate Spectral Density of a Time Series

```{r}
# Periodogramm
# Das Periodogramm ist das Pendant zum Korellogramm auf Spektralebene
# Es ist die abgebildete Fouriertransformation der Autokovarianzfunktion 
data_period <- spec.pgram(data_ts, taper = 0, pad = 0, fast = TRUE, demean = FALSE, 
           detrend = TRUE, plot = TRUE, na.action = na.fail)
#  Frequenz λ = 1: signiﬁkanter Ausschlag stattﬁndet
#  => vorliegende Muster wiederholt sich jede volle Frequenz / jedes Jahr
#  Die restlichen Ausschläge sind bereits zu zufällig, um sie signiﬁkant 
#                                                    einordnen zu können.

data_period_tbl <- as_tibble(data_period$freq) %>% 
  mutate(Frequency = value,
         Spectrum = data_period$spec)
ggplot(data_period_tbl, aes(Frequency, Spectrum)) +
  geom_line() +
  labs(x = paste("Frequency\n", "bandwidth = ", data_period$bandwidth)) +
  scale_y_log10() +
    ggtitle( paste("Time Series ", data_period$method))
```


```{r Beispiele Rest all, eval=FALSE}

# Beispiel 3.3

   n <- 50
   a <- c(0.5,-0.9)
   e <- rnorm(n+50)    
   x <- e 
   t <- 3
   while(t < (n+50)){ t <- t+1; x[t] <- sum(a*x[t-c(1,2)]) + e[t] } 
   ts.plot(x)
   lines(c(50,50),c(-4,6),lty=2)

# Beispiel 3.9

   y <- scan("./Data_Schlittgen/herzschlag.dat")
   n <- length(y)
   RSS <- rep(0,4)
   AIC <- rep(0,4)
   BIC <- rep(0,4)
   for (p in c(1:4)){
     out <- ar(y,order.max=p,aic=FALSE,method="ols")
     res <- out$resid[-c(1:p)]
     RSS[p] <- sum((res-mean(res))^2) 
     AIC[p] <- log(RSS[p]/n) + 2*p/n
     BIC[p] <- log(RSS[p]/n) + log(n)*p/n 
     }
   s2 <- RSS/n
   round(rbind(c(1:4),s2,AIC,BIC),3) 

# Beispiel 3.10

   DiMe <- scan("./Data_Schlittgen/diabetes.dat")
   DiMe <- ts(DiMe,start=c(1979,1),frequency=12) 
   plot(DiMe) 
   y <- ts(DiMe,frequency=1) 
   y <- y-mean(y)
   n <- length(y)
   acf(y,lag.max=20,ci=FALSE)
   acf(y,lag.max=20,type="partial") 
   m1 <- arima(y,order=c(3,0,0),include.mean=FALSE)
   m2 <- arima(y,order=c(3,0,0),include.mean=FALSE,fixed=c(NA,0,NA))
   m3 <- arima(y,order=c(1,0,0),include.mean=FALSE)
   -2*m1$loglik+log(n)*3  
   -2*m2$loglik+log(n)*2
   -2*m3$loglik+log(n)*1
   source("./Data_Schlittgen/tsutil.r") 
   LjungBoxPierceTest(m1$residuals,n.par=3,maxlag=18)
   LjungBoxPierceTest(m2$residuals,n.par=2,maxlag=18)
   LjungBoxPierceTest(m3$residuals,n.par=1,maxlag=18) 
   qqnorm(m2$resid)
   abline(0,sd(m2$resid)) 

# Beispiel 3.16

   n <- 50
   e <- rnorm(n+7)
   y <- e[-c(1:7)] + 0.8*e[-c(1:6,n+7)] - 1.8*e[-c(1:3,n+(4:7))]
        -1.64*e[-c(1:2,n+c(3:7))]-2.50*e[-(n+c(1:7))] 
   a <- acf(y,lag.max=15,ci.type = "ma")
   lines(c(3,15),rep(2*sqrt((1+2*a$acf[2]^2+2*a$acf[3]^2)/n),2))
   lines(c(3,15),rep(-2*sqrt((1+2*a$acf[2]^2+2*a$acf[3]^2)/n),2))

# Beispiel 3.17

   y <- scan("./Data_Schlittgen/tremor.dat") 
   ts.plot(y) 
   par(mfrow=c(2,1))
   a <- acf(y,lag.max=50,ci.type = "ma")
   p <- acf(y,lag.max=50,type="partial",ylab="PACF") 
   out <- arima(y,order=c(2,0,2))
   out 
   S <- vcov(out)
   D <- diag(1/sqrt(diag(S))) 
   R <- round(D%*%S%*%D,3)
   colnames(R) <- rownames(R)<-c("ar1","ar2","ma1","ma2","intercept") 
   R
   source("./Data_Schlittgen/tsutil.r")
   LjungBoxPierceTest(out$resid,4,48) 

# Beispiel 3.18

   library(TSA) 
   eacf(y, ar.max = 7, ma.max = 13)

# Beispiel 3.21

   Unfall<-scan("./Data_Schlittgen/unfall.dat")
   Unfall<-ts(Unfall,start=c(1974,1),frequency=12)  
   y <- window(Unfall,start=c(1974,1),end=c(1990,12))
   y <- log(y)
   y1 <- as.vector(diff(y,12)) 
   acf(y1,lag.max=50,ci.type = "ma")
   acf(y1,lag.max=50,type="partial") 
   out <- arima(y,order=c(1,0,0),
          seasonal=list(order=c(2,1,0),period=12))   
   LjungBoxPierceTest(out$resid,3,48) 

# Beispiel 4.1

   dat<-read.table("./Data_Schlittgen/bip.dat",header=TRUE)
   bip <- ts(dat[,3],start=c(1970,1),frequency=4)
   y <- window(bip,start=c(1970,1),end=c(2007,4))
   plot(y)
   source("./Data_Schlittgen/tsutil.r")
   acfpacf(diff(y),40)
   mean(diff(y))
   library(urca)
   out<-ur.df(y,type="drift",lags=4,selectlags="Fixed")
   summary(out)  

# Beispiel 5.1
   
   bier <- scan("./Data_Schlittgen/bier.dat")
   bier <- ts(bier,start= c(1956,1),frequency=12) 
   y <- window(bier,start=c(1990,1)) 
   library("forecast")
   out <- ets(y,damped=T)  
   p <- predict(out,n.ahead=24) 
   plot(p)     

# Beispiel 5.3
  	
   wine <- scan("./Data_Schlittgen/rotwein.dat")      
   y <- ts(wine[,1],start=c(1980,1),frequency=12) 
   plot(y) 
   source("./Data_Schlittgen/tsutil.r") 
   BoxCox(y,10) 
   y <- log(y) 
   vartable(y,12)  
   a <- acf(as.vector(diff(y,12)),lag.max=50,ci.type="ma")
   p <- acf(as.vector(diff(y,12)),lag.max=50,type="partial")  
   out <- arima(y,order=c(1,0,1),seasonal=list(order=c(0,1,1),
          period=12))  
   LjungBoxPierceTest(out$residuals,4,50) 
   p <- predict(out,n.ahead=24)
   new.dat.1 <- ts(exp(p$pred),start=c(1995,6),frequency=12)
   new.dat.2 <- ts(exp(p$pred-1.96*p$se),start=c(1995,6),frequency=12)   
   new.dat.3 <- ts(exp(p$pred+1.96*p$se),start=c(1995,6),frequency=12) 
   ts.plot(exp(y),new.dat.1,new.dat.2,new.dat.3, lty=c(1,1,2,2))  

# Beispiel 5.4
  	
   jlast <- scan("./Data_Schlittgen/jlast.dat")
   y <- ts(jlast,start=1954,frequency=1)
   y1 <- window(y,start=1954,end=1978)
   t1<- 1953+c(1:length(y1))
   out <- lm(y1~t1[1:25])
   acfpacf(out$residuals,10) 
   out <- arima(y1,order=c(1,0,0),xreg=t1)
   out 
   p <- predict(out,n.ahead=12,newxreg = c(1979:1990),se.fit=TRUE)
   new.dat.1 <- ts(p$pred,start=1979,frequency=1)
   new.dat.2 <- ts(p$pred-1.96*p$se,start=1979,frequency=1)   
   new.dat.3 <- ts(p$pred+1.96*p$se,start=1979,frequency=1)
   par(mar=c(4,4,1,1)) 
   ts.plot(y,new.dat.1,new.dat.2,new.dat.3,lty=c(1,1,2,2))       

# Beispiel 6.5

   y <- scan("./Data_Schlittgen/luchs.dat") 
   y <- log10(y)
   ts.plot(y)
   lambda <- 1/9.5
   t <- c(1:length(y))
   co <- cos(2*pi*lambda*t)
   si <- sin(2*pi*lambda*t)
   out <- lm((y-mean(y))~co+si-1) 
   plot(t,y,type="l")
   lines(t,mean(y)+out$fitted.values,lty=3)   
   
# Beispiel 6.8

   y <- scan("./Data_Schlittgen/steuern.dat")
   source("./Data_Schlittgen/tsutil.r") 
   fp <- periodogram(y,100)
   plot(fp[,1],fp[,2],type="l")

# Beispiel 6.11

   spreis <- scan("./Data_Schlittgen/schweinepreis.dat")
   y <- ts(spreis,start=c(1894,1),frequency=12) 
   out <- stl(y,s.window=6) 
   e <- out$time.series[,3]
   n <- length(e)
   Ffreq <- length(seq(1:(n/2))/n) 
   source("./Data_Schlittgen/tsutil.r")
   p <- periodogram(e,Ffreq)  
   plot(p[,1],p[,2],type="l")
   m <- mean(p[,2])
   1-(1-exp(-max(p[,2])/m))^trunc((n-1)/2)    

# Beispiel 6.13

   t <- c(1:n)
   co <-  cos(2*pi*(1/48)*t)
   si <-  sin(2*pi*(1/48)*t)
   out <- lm(e~co+si)  
   wntest(out$resid,0.05,k=3)

# Beispiel 6.23

   y <- scan("./Data_Schlittgen/biporig.dat") 
   y <- ts(y,start=c(1970,1),frequency=4)
   source("./Data_Schlittgen/tsutil.r")
   yf <- bandfilt(y-mean(y),20,3,5)      
   plot(y,xlab="Zeit",ylab="BIP")
   lines(yf+mean(y))   
   lines(y-yf) 

# Beispiel 6.31

   wh <- scan("./Data_Schlittgen/whormon.dat")
   source("./Data_Schlittgen/tsutil.r")
   out <- specest(wh[-1],48,0.1,win="perwinba",conf=0.95) 
   ts.plot(wh)
   specplot(out)  

# Beispiel 6.33

   y <- scan("./Data_Schlittgen/ibm.dat")
   y <- diff(log(y))
   ts.plot(y)
   source("./Data_Schlittgen/tsutil.r") 
   n <- length(y)
   nseg <- 60  
   seg <- -9
   spec <- NULL
   t <- NULL
   while(seg < (n-nseg)){
     seg <- seg + 10
     out <- specest(y[seg:(seg+nseg)],50,0.2)
     f <- out[,1]
     t <- cbind(t,seg)
     spec <- cbind(spec,out[,2])
     }
     persp(f,t,spec,ticktype="detailed",xlab="Frequenz",ylab="Zeit",
           zlab="Spektrum",theta=35,d=35) 

# Beispiel 7.6

   library(longmemo)
   data(NileMin)
   k <- c(20:200)
   source("./Data_Schlittgen/tsutil.r")
   RNil <- RS(NileMin,k) 
   plot(RNil[,1],RNil[,3], type = "p",log ="xy",pch=16,xlab="ln(k)", 
        ylab="ln(R/S)") 
   lk <- log(RNil[,1]) 
   lR <-log(RNil[,3])  
   coef <- coefficients(lm(lR~lk))
   print(coef) 
   a <- coef[1]
   b <- coef[2]
   curve(exp(a)*x^b,add = T,lwd=2)

# Beispiel 7.8

   source("./Data_Schlittgen/tsutil.r")
   out <- periodogram(NileMin,663/2)
   x <- log(4*sin(pi*out[,1])^2)
   y <- log(out[,2])
   h <- 4
   out1 <- lm(y[h:26]~x[h:26]) 
   library(MASS)
   out2 <- rlm(y[h:26],x[h:26],method = "M",psi = psi.bisquare) 

# Beispiel 7.10

   library(fracdiff)
   out <- fracdiff(NileMin,nar=10)
   summary(out) 

# Beispiel 7.11

   library(arfima)
   data(tmpyr) 
   tmpyrs <- window(tmpyr,start=1659,end=1900)
   out <- arfima(tmpyrs,order=c(1,0,1)) 
   res <- residuals(out)
   r <- res$Mode2
   acfpacf(r,100)
   summary(out)
   p <- predict(out,n.ahead=76)
   plot(window(tmpyr,start=1800), xlab="Jahr",ylab="Temperatur",
        type="l")
   lines(c(1901:1976),p[[2]]$Forecast,lwd=2)
   lines(c(1901:1976),p[[2]]$uppernp,lwd=2)
   lines(c(1901:1976),p[[2]]$lowernp,lwd=2)


# Beispiel 8.11

   dat <- read.table("./Data_Schlittgen/speiseeis.dat",header=T)   
   y1 <- dat[,2]   
   y2 <- dat[,5]
   ts.plot(y1)
   ts.plot(y2)
   a1 <- arima(y1,order=c(3,0,0))
   a2 <- arima(y2,order=c(3,0,0)) 
   ccf(y1,y2,lag.max=10)
   ccf(a1$resid,a2$resid,lag.max=10) 

# Beispiel 8.13

   dat <- read.table("./Data_Schlittgen/lith.dat",header=T)
   N<-ts(dat[,1])
   G<-ts(dat[,2])
   source("./Data_Schlittgen/tsutil.r")
   bi <- bispeces(N,G,20,win="bartlett")
   plot(bi[,1],bi[,2],type="l")
   plot(bi[,1],bi[,3],type="l") 

# Beispiel 8.19

   n<-101
   komp <- 2
   S <- matrix(c(1.0,0,0,1.0),2,2,byrow=T)    
   C <- chol(S)
   A <- matrix(c(0.5,0.3,-1.5,0.8),2,2,byrow=T)
   e <- matrix(rnorm(2*(n+komp)),2,n+komp)
   e <- C%*%e
   y <- e
   for(t in c(2:(n+komp))){
     y[,t] <- A%*%e[,t-1] + e[,t]
     }
   y <- t(y[,(komp+1):(n+komp)])  
   source("./Data_Schlittgen/tsutil.r")
   a <- acfmat(y,5)

# Beispiel 8.20

   n <- 300
   S <- matrix(c(2.0 , 1.8 , 1.8 , 3.0),2,2, byrow=T)
   C <- chol(S)
   A <- matrix(c(0.5 , 0.3 , -1.5 , 0.8),2,2, byrow=T)
   e <- matrix(rnorm(2*(n+200)),2,n+200)
   y <- e
   for (t in c(2:(n+200))){ y[,t] <- A%*%y[,t-1] + C%*%e[,t]  }
   y<-t(y[,201:(n+200)])
   source("./Data_Schlittgen/tsutil.r")
   out <- pacfmat(y,5) 
  
# Beispiel 8.21
 
   dat <- read.table("./Data_Schlittgen/papier.dat",header=T)
   attach(dat) 
   paperm <- cbind(height,weight-mean(weight))  
   ts.plot(paperm,lty=c(1,2),lwd=c(1.5,2),xlab="",ylab="") 
   source("./Data_Schlittgen/tsutil.r") 
   out <- pacfmat(dat,10)
   out$pval 
   print(out$M1,quote=F)  
   VARselect(paperm,lag.max = 10, type =  "none") 
   out <- VAR(dat,3) 
   summary(out) 
   res <- resid(out)
   out1 <- pacfmat(res,10)  
   out <- VAR(paperm,p=3,type = "none") 
   summary(out)
   restriction <- matrix(c(1, 1, 1, 0, 0, 1, 
                           1, 1, 1, 1, 0, 0),
                           nrow=2, ncol=6, byrow=TRUE)
   out1 <- restrict(out,method="man",resmat=restriction)  
   out2 <- pacfmat(resid(out1),10)
   out2$pval                        
   print(out2$M1,quote=F)
 
# Beispiel 8.22
 
   zins<-read.table("./Data_Schlittgen/dominanz.dat")
   zins <- zins[,c(2,1)]
   colnames(zins)<-c("X","Y") 
   zins<-ts(zins,start=c(1981,1),frequency=12)
   source("./Data_Schlittgen/tsutil.r") 
   dzins <- diff(zins)
   est <- VAR(dzins,p=3)
   causality(est,cause="X")
   causality(est,cause="Y") 
   out <- Grangercaus(dzins[,1],dzins[,2],4) 

# Beispiel 8.25
    
   y <- cumsum(rnorm(100)) + rnorm(100,sd=sqrt(0.5))
   z <- cumsum(rnorm(100)) + rnorm(100,sd=sqrt(0.0625))  
   out <- lm(z~y)  
   plot(y,ylim=c(min(y,z),max(y,z)),type="l")
   lines(z,lwd=1.75,lty=2)
   plot(y,z ,xlab="x",ylab="y")
   abline(out)
   plot(c(1:100),out$residuals,type="l")  

# Beispiel 8.26
  
   zins <- read.table("./Data_Schlittgen/dominanz.dat")
   zins <- zins[,c(2,1)]
   zins <- ts(zins,start=c(1981,1),frequency=12) 
   X <- zins[,1]
   Y <- zins[,2]  
   library(urca)
   out <- ur.df(X,type="none",lags=1,selectlags="Fixed")
   summary(out)
   out <- ur.df(Y,type="none",lags=1,selectlags="Fixed")
   summary(out) 
   out <- lm(Y~X) 
   out <- ur.df(out$residuals,type="none",lags=1,selectlags="Fixed")
   summary(out)
   qunitroot(0.05,N=length(Y),trend="nc")

# Beispiel 9.2 
  
   dat <- scan("./Data_Schlittgen/bisam.dat") 
   y <- ts(log10(dat))
   n <- length(y)
   t1 <- c(1:n)
   t2 <- t1^2 
   out1 <- lm(y~t1)
   out2 <- lm(y~t1+t2)  
   plot(y) 
   lines(t1,out1$fitted.values)  
   lines(t1,out2$fitted.values,lwd=1.75)  
   source("./Data_Schlittgen/tsutil.r")
   acfpacf(out2$residuals,15) 
   out3 <- arima(y,order=c(2,0,0),xreg=cbind(t1,t2)) 
   summary(out2)
   out3 

# Beispiel 9.3 

   dat <- scan("./Data_Schlittgen/verk?ufe.dat") 
   y <- ts(dat,start=c(1965,1),frequency=12) 
   plot(y,xlab="Jahr",ylab="Verk?ufe") 
   y <- log(y) 
   source("./Data_Schlittgen/tsutil.r") 
   vartable(y,12)  
   acfpacf(diff(y,12),20) 
   n <- length(y) 
   t <- c(1:n)  
   out <-arima(y,order=c(0,0,2),seasonal=list(order=c(1,1,0),
         period=12), xreg=t)  
   LjungBoxPierceTest(out$residuals,3,24)  

# Beispiel 9.5 

   dat <- scan("./Data_Schlittgen/blackout.dat")
   y <- ts(dat,start=1961,frequency=52) 
   plot(y,xlab="Woche",ylab="Anzahl Geburten") 
   n <- length(y)
   It <- rep(0,n)
   It[292:295] <- 1
   y1 <- window(y,start=c(1961,1),end=c(1966,30)) 
   source("./Data_Schlittgen/tsutil.r")
   vartable(y1,52) 
   acfpacf(diff(y1),70)  
   out <- arima(y1,order=c(0,1,52),fixed=c(NA,rep(0,50),NA))
   acfpacf(out$residuals,70)  
   LjungBoxPierceTest(out$residuals,2,60)
   out <- arima(y,order=c(0,1,52),xreg=It,fixed=c(NA,rep(0,50),NA,NA))
   out
   LjungBoxPierceTest(out$residuals,2,60)

# Beispiel 9.6 

   Unfall<-scan("./Data_Schlittgen/unfall.dat")
   y <- ts(Unfall,start=c(1974,1),frequency=12)  
   y <- log(y)
   y1 <- window(y,start=c(1974,1),end=c(1990,12))
   source("./Data_Schlittgen/tsutil.r")
   vartable(y1,12) 
   acfpacf(diff(y1,12),50)  
   out <- arima(y1,order=c(1,0,0),
           seasonal=list(order=c(2,1,0),period=12))  
   acfpacf(out$residuals,50)                
   LjungBoxPierceTest(out$residuals,3,48) 
   I <- rep(1,length(y))
   I[1:length(y1)] <- 0  
   out <- arima(y,order=c(2,0,0),
          seasonal=list(order=c(2,1,0),period=12),xreg=I) 
   acfpacf(out$residuals,50)                  
   LjungBoxPierceTest(out$residuals,4,48)

# Beispiel 9.9 
 
   dat <- read.table("./Data_Schlittgen/alkeink.dat",header=TRUE) 
   attach(dat)  
   dEink <- diff(Eink)
   dEink <- dEink-mean(dEink)
   dAlk <- diff(Alk)  
   source("./Data_Schlittgen/tsutil.r") 
   acfpacf(dEink,20) 
   out <- arima(dEink,order=c(2,0,0),include.mean=FALSE) 
   out
   acfpacf(out$resid,20) 
   xw <- out$resid 
   yw <- filter(dAlk,c(1,-out$coef),method="convolution",sides=1) 
   yw <- yw[-c(1,2)]            
   xw <- xw[-c(1,2)] 
   cc <- ccf(xw,yw,lwd=2)
   nu <- cc[c(0,-2,-4)]
   nu <- c(nu$acf[1],0,nu$acf[2:3])
   se <- sd(xw)
   sy <- sd(yw)
   nu <- nu*sy/se 
   U <- filter(dEink,nu,method="convolution",sides=1) 
   N <- dAlk-U
   N <- N[-c(1:3)]
   acfpacf(N,20)
   out <- arima(N,order=c(2,0,0))
   out 
   acfpacf(out$resid,20)
   n <- length(dEink)
   trans <- cbind(dEink[-c(1:4)],dEink[-c(1:2,(n-1):n)],
            dEink[-c((n-3):n)])    
   out <- arima(dAlk[-c(1:4)],order=c(2,0,0),xreg=trans)
   out

# Beispiel 10.10
   
   library(dlm)                                      
   co2 <- scan("./Data_Schlittgen/schauinsland.dat")
   co2 <- ts(co2,start = 2005,frequency=12)
   dlmco <- dlmModPoly(2) + dlmModSeas(12)m1 <- c(382,0.1,rep(0,11))
   c1 <- diag(c( 0.1, 0.1, rep(100,11)))
   
   buildFun <- function(x) { 
      W(dlmco)[1:3,1:3] <- diag(exp(x[1:3]))
      V(dlmco) <- exp(x[4]) 
      C0(dlmco) <- c1
      m0(dlmco) <- m1 
      return(dlmco)
   }              

fit <- dlmMLE(co2, parm=rep(1,4), build=buildFun)
fit$conv
dlm.co2 <- buildFun(fit$par)                                              
coFilter <- dlmFilter(co2, mod=dlm.co2)
coSmooth <- dlmSmooth(coFilter) 

plot(co2,type="o") 
lines(dropFirst(coFilter$m[,1]))
lines(dropFirst(coSmooth$s[,1]))
plot(dropFirst(coSmooth$s[,3]))

fut1 <- dlmForecast(coFilter, n=12)
x <- cbind(co2,fut1$f,fut1$f-1.96*sqrt(unlist(fut1$Q)),
           fut1$f+1.96*sqrt(unlist(fut1$Q)))                                
plot.ts(x,plot.type="s",lty=c(1,1,2,2)) 
points(2005+28/12,co2[29])                                                                 
 
# Beispiel 11.4 
     
   P <- matrix(c(0.8,0.2,0.1,0.9),2,2,byrow=TRUE) 
   e <- rnorm(250) 
   S <- runif(250)
   y1 <- rep(1,250)
   y2 <- rep(1,250) 
   m1 <- 0
   m2 <- 10 
   S[1] <- 1*(S[1]<=0.5) + 2*(S[1]>0.5)
   for (t in c(2:250)){ 
       if (S[t-1] == 1){ S[t] <- 1*(S[t]<=P[1,1])+2*(S[t]>P[1,1]) }
       if (S[t-1] == 2){ S[t] <- 1*(S[t]<=P[2,1])+2*(S[t]>P[2,1]) }
       if (S[t] == 1){y1[t] <- m1+0.8*(y1[t-1]-m1)+e[t] 
                      y2[t] <- m1+0.8*y2[t-1]+ e[t] }
       if (S[t] == 2){y1[t] <- m2+0.8*(y1[t-1]-m2)+e[t] 
                      y2[t] <- m2+0.8*y2[t-1]+e[t] }
       }      
   ts.plot(y1[51:250])
   ts.plot(y2[51:250])  

# Beispiel 11.6

   dat <- read.table("./Data_Schlittgen/bip.dat",header=T)
   y <- ts(dat[,3],start=c(1970,1),frequency=4)
   y1 <- window(y,start=c(1970,1),end=c(2007,4)) 
   library(mFilter)
   out <- bkfilter(y1,pl=4.4,pu=35,nfix=12,drift=FALSE) 
   y2 <- na.omit(out$cycle)
   library(MSwM) 
   L <- rep(1,length(y2))
   mod <- lm(y2 ~ L - 1)
   out <- msmFit(mod, k=2, sw=c(T,T,T,T,T,T),p=4)
   summary(out)
   plotProb(out,1)
   plotDiag(out,1,3)

# Beispiel 11.9 

   dat<-read.table("./Data_Schlittgen/dax.dat",header=T)
   attach(dat)  
   dax<-dax30[(jahr>2008)&(jahr<2011)]
   rendite <- ts(diff(log(dax))) 
   par(mfrow=c(2,1)) 
   plot(rendite,xlab="Zeitindex",ylab="rendite",xaxt="n")  
   plot(rendite^2,xlab="Zeitindex",ylab=expression(rendite^2))  
   source("./Data_Schlittgen/tsutil.r")  
   acfpacf(rendite,50) 

# Beispiel 11.10 

   library(tseries)
   out <- garch(rendite,order=c(0,8))
   summary(out) 
   res <- out$residuals[-c(1:8)] 
   par(mfrow=c(1,2))
   acf(res^2,lag.max=50,type="partial") 
   qqnorm(res,main="")
   abline(mean(res),sd(res),col="grey",lwd=2)
   M <- 100
   out1 <- acf(res^2,M)
   a <- out1$a[-1]
   n <- length(res)
   r2 <- n*rev(cumsum(rev(a^2)))
   out1 <- NULL
   for (i in c(9:61)){out1<-rbind(out1, round(c(i,r2[i+1],
                      1-pchisq(r2[i],M-i)),2)) }
   print(out1) 

# Beispiel 11.11 

   n <- 300
   a <- -0.9
   b <- c(0.01,0.4,0.4)
   e <- rnorm(n+100,0.2) 
   x <- e 
   t <- 4
   while(t < (n+100)){ 
    t <- t+1 
    e[t] <- e[t]*sqrt(b[1] + sum(b[3:2]*(e[(t-2):(t-1)]^2))) 
    x[t] <- a*x[t-1] + e[t] 
    } 
   x <- x[101:(n+100)]
   ts.plot(x)

# Beispiel 11.12 

   dat <- read.table("./Data_Schlittgen/mdax.dat",header=T)
   attach(dat)  
   mdax <- mdax[(jahr>2008)&(jahr<2011)]
   rendite <- ts(diff(log(dax)))
   out <- garch(rendite,order=c(1,2))
   summary(out)
   res <- out$residuals[-c(1:2)]
   qqnorm(res)
   abline(mean(res),sd(res))
   source("./Data_Schlittgen/tsutil.r")
   LjungBoxPierceTest(res^2,3,60) 
 

# Beispiel 12.1  

   dat<- read.table("./Data_Schlittgen/grundwasser.dat",header=T) 
   fehl <- dat[is.na(dat[,2]),1]  
   hand <- dat[fehl,3] 
   attach(dat)  
   source("./Data_Schlittgen/tsutil.r") 
   outar <- missar(y,10) 
   outls <- missls(y,10)
   ts.plot(outls) 
   lines(dat[,1],outar$y) 
   points(fehl,hand,pch=8) 

# Beispiel 12.2  

   dat <- read.table("./Data_Schlittgen/oxygen.dat",header=TRUE) 
   attach(dat) 
   plot(zeit,delta18O,type="o",xlab="Zeit",
     ylab=expression(paste(delta^18,"O"))) 
   rug(zeit)  

# Beispiel 12.3  

   library(nlme)
   d <- Variogram(delta18O,dist(zeit))
   attach(d)
   s <- smooth.spline(dist,variog)
   x <- s$x[s$x<100]
   y <- s$y[s$x<100]   
   plot(x,y,type="l")

# Beispiel 12.5  

   dat <- read.table("./Data_Schlittgen/luhormon.dat")
   x <- dat[,2]
   source("./Data_Schlittgen/tsutil.r")
   out <- arima(x,order=c(1,0,0))  
   out1 <- outidentify(x,out,alpha=0.05)
   plot(dat[,1],x,type="l")
   points(dat[c(2,9,23),1],x[c(2,9,23)]+0.35,pch=8)  
   out1$out

# Beispiel 12.6  

   dat <- read.table("./Data_Schlittgen/fichte.dat")
   y <- dat[,2] 
   ts.plot(y)
   source("./Data_Schlittgen/tsutil.r")
   acfpacf(diff(y[1:36]),10) 
   Imp <- rep(0,length(y))
   Imp[dat[,1]==1990] <- 1 
   out <- arima(y,order=c(0,1,1),xreg=Imp)
   out 

# Beispiel 12.7  

   g  <- smoothrb(y,15,5) 
   out <- lm((y-g)~Imp)
   acfpacf(out$resid,15)

# Beispiel 12.8  

   y <- scan("./Data_Schlittgen/auftragseingang.dat")
   y <- ts(y,start=c(1972,1),frequency=12)
   out <- stl(y,s.window=9)
   plot(out)   
    

```

