---
title: "Coronavirus SARS-CoV-2 / Covid-19 Shiny"
author: "Wolfgang Vollmer"
date: '`r Sys.Date()`'
link-citations: yes
cite-color: "green"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = TRUE, echo = FALSE, warning = FALSE,      
                      message = FALSE, fig.width = 7, fig.asp = 0.618)


library(flexdashboard)
library(tidyverse)
library(magrittr)
library(lubridate)
library(slider) # for rolling analysis using window functions
library(fpp3)  # tsibble, tsibbledata, fable, and feasts packages & some tidyverse
library(slider) # sliding window functions - rolling averages, cumulative sums
library(DT)      # R interface to the JavaScript library DataTables
library(patchwork) # package for composing plots
           # https://www.data-imaginist.com/2019/patch-it-up-and-send-it-out/
# library(gghighlight) 
# # https://cran.r-project.org/web/packages/gghighlight/vignettes/gghighlight.html
# # library(gridExtra)
# # library(janitor)
# library(plotly)
library(highcharter)
library(dygraphs)  # R interface to the dygraphs JavaScript charting library

```


```{r initialization, eval = TRUE, include = FALSE}

################################################################################
##                                                                            ##
## Corona Virus -                                                             ##
##       Analyze Time Series of Confirmed, Death and Recovered Cases          ##
##                                                                            ##
##                                          Wolfgang Vollmer,   July  2, 2020 ##
##                                              First Version: March 12, 2020 ##
##                                                                            ##
## URL:                                                                       ##
## https://github.com/WoVollmer/R-TimesSeriesAnalysis/tree/master/Corona-Virus##  
################################################################################

######  variables clean up, library() and	source() statements 
rm(list=ls()) # deletes all existing objects / variables !!
# Prog.Start <- Sys.time()


theme_replace(
  plot.title = element_text(
    hjust = 0.5, face = "bold.italic", color = "darkcyan", size = 12),
  plot.subtitle = element_text(
    hjust = 0.5, face = "italic", color = "darkcyan")
)
x_axis_theme <- element_text(size = 14)
```


```{r settings}
device <- "desktop" # "notebook"  # to define setwd() and data path
# defined as params  metadata in YAML header
# device <- params$device

compare_countries <- c("Austria", "France", "Germany", "Italy", "India",
                       "South Korea", "Spain",  "United States of America")
countries <- c("China", compare_countries)
countries_exp_growth <- c("World", "China", "Austria", "France", "Germany", "Italy", 
                       "South Korea", "Spain",  "United States of America")
country_select <- "Germany"

span <- 7 #  for rolling mean over 7 days
q <- floor(span/2) # since 2q +1 = span !

range_reg <- 7   # important - no Cases value = 0 are allowed => log(0) = inf !
# changed from 9 -> 7 days, 
# but whole week is necessary to get rid of weekly fluctuations
range_forcast <- 14  # 14days forecast => unclass(last_date + 1 + range_forcast -1)
range_daily_reg <- 21  # one week is to short, confidence level to large !!
range_cfr <- 14  # 14days cfr past period length
lag_n <- 11  # average confirmed lag - for all countries

```

```{r path on desktop vs. notebook, eval = TRUE}
# if (device == "desktop") {
#   setwd("D:/Wolfgang/Programs-R/R-TimeSeriesAnalysis/Corona-Virus")
#   
#   data_path <- 
#     "D:/Wolfgang/WoDocs/GitHub/COVID-19/csse_covid_19_data/csse_covid_19_time_series"
#   
# } else if (device == "notebook") {
#   # attention: here we have (whyever) TimesS.. (Time + s) instead of TimeS..
#   setwd("C:/Wolfgang/Programs-R/R-TimesSeriesAnalysis/Corona-Virus")
#   
#   data_path <- 
#     "C:/Wolfgang/Programs-R/COVID-19/csse_covid_19_data/csse_covid_19_time_series"
# } else {
#   stop("no valid device outlined")
# }

######  Plot and util functions
######  ######  Plot and util functions
source("ggts_corona.R") # ggplot2 functions for time series plots

```

```{r save read rds data}

# corona_country <- readRDS("corona_country.RDS")
corona_population <- readRDS("./data/corona_population.RDS")

first_date <- min(corona_population$Date)
last_date <- max(corona_population$Date)

```

```{r complete data}
corona_all_data_wide <- corona_population %>% 
  pivot_wider(names_from = Case_Type, 
              values_from = c(Cases, Daily_Cases, 
                              
                              Cases_100k, Daily_Cases_100k, 
                              Cases_rol_mean, Cases_100k_rol_mean)) %>% 
  rename(Confirmed = Cases_Confirmed,
         Deaths = Cases_Deaths,
         Daily_Confirmed = Daily_Cases_Confirmed,
         Daily_Deaths = Daily_Cases_Deaths,
         Conf_100k = Cases_100k_Confirmed,
         Deaths_100k = Cases_100k_Deaths,
         Daily_Conf_100k = Daily_Cases_100k_Confirmed,
         Daily_Deaths_100k = Daily_Cases_100k_Deaths,
         Conf_rol_mean = Cases_rol_mean_Confirmed, 
         Deaths_rol_mean = Cases_rol_mean_Deaths,
         Conf_100k_rol_mean = Cases_100k_rol_mean_Confirmed, 
         Deaths_100k_rol_mean = Cases_100k_rol_mean_Deaths) %>% 
  dplyr::select(Country, Population, Date, 
                Confirmed, Daily_Confirmed, Conf_rol_mean, Conf_100k, 
                Daily_Conf_100k, Conf_100k_rol_mean, 
                Deaths, Daily_Deaths, Deaths_rol_mean, Deaths_100k, 
                Daily_Deaths_100k, Deaths_100k_rol_mean)

corona_abs_wide <- corona_all_data_wide %>% 
  dplyr::select(!contains("_100k"), -Population)

corona_rel_wide <- corona_all_data_wide %>% 
  dplyr::select(Country, Date, contains("_100k"))

# View(corona_all_data_wide %>% filter(Date == last_date))
```


## Cumulated and Daily Trend


```{r}

country <- "World"
fig_width_trend <- 10 # fig.width = fig_width_trend 7
fig_asp_trend <- 0.9

weeks <- 12

```


```{r eval = FALSE}

shinyAppDir(
  system.file("sh_trend_daily"),
  options = list(width = "100%", height = 700)
)
```


```{r  Time Series Diagram Worldwide, fig.width = fig_width_trend, fig.asp = fig_asp_trend}

library(shiny)

shinyApp(
  
  ui = fluidPage(
    # Input: Selct Country for plot ----
    titlePanel("Cumulated and Daily Cases over Time - Country 1"),
    fluidRow(column(width = 6,
                    selectInput(
                      'country', label = 'Select Country:',
                      choices = unique(corona_population$Country), 
                      selected = "World")),
             # Input: Specify the number of weeks for plot ----
             # numericInput("weeks", "Number of Weeks for plot range:", 6, 
             #              min = 2, max = 28),
             column(width = 6,
                    sliderInput("weeks", "Number of Weeks for plot range:", 
                                weeks, min = 2, max = 28))),
    plotOutput("trend_plot")
  ),
  
  server = function(input, output) {
    output$trend_plot = renderPlot({
      ggts_trend_daily(corona_population %>% 
                         filter(Country == input$country), 
                       input$country, weeks = input$weeks)
    })
  },
  
  options = list(height = 550)
)

```


```{r  shiny select country, fig.width = fig_width_trend, fig.asp = fig_asp_trend}

shinyApp(
  
  ui = fluidPage(
    # Input: Selct Country for plot ----
    titlePanel("Cumulated and Daily Cases over Time - Country 2"),
    fluidRow(column(width = 6,
                    selectInput(
                      'country', label = 'Select Country:',
                      choices = unique(corona_population$Country), 
                      selected = "Germany")),
             # Input: Specify the number of weeks for plot ----
             # numericInput("weeks", "Number of Weeks for plot range:", 6, 
             #              min = 2, max = 28),
             column(width = 6,
                    sliderInput("weeks", "Number of Weeks for plot range:", 
                                weeks, min = 2, max = 28))),
    plotOutput("trend_plot")
  ),
  
  server = function(input, output) {
    output$trend_plot = renderPlot({
      ggts_trend_daily(corona_population %>% 
                         filter(Country == input$country), 
                       input$country, weeks = input$weeks)
    })
  },
  
  options = list(height = 550)
)

```


## Daily Trend with Rolling Mean


```{r dygraph_plot Daily Rolling Mean, eval = TRUE}
shinyApp(
  
  ui = fluidPage(
    # Input: Select Country for plot ----
    titlePanel("Rolling Mean of Daily Cases"), 
    selectInput(
      'country', label = 'Select Country:',
      choices = unique(corona_population$Country), selected = "Germany"),
    dygraphOutput("dygraph_plot")
  ),
  
  server = function(input, output) {
    output$dygraph_plot = renderDygraph({
      # input <- list()
      # input$country <- "Germany"
      
      data <- corona_abs_wide %>% 
        filter(Country == input$country) %>% 
        ungroup()
      
      # change tibble in xts object
      index <- data$Date
      data_xts <- xts::xts(
        data %>% dplyr::select(Daily_Confirmed, Conf_rol_mean, 
                               Daily_Deaths, Deaths_rol_mean),
        order.by = index) 
    
      plot_dygraph_daily(data_xts, input$country, last_date, weeks = weeks)
    })
  },
  
  options = list(height = 600)
)
```



```{r Confirmed Cases with Reproduction Number}
# infectivity profile w(t) w/ w(t= day_1 & day>=11)=0:
infectivity <- c((0:3)/3, 1, (5:0)/5)
names(infectivity) <- seq_along(infectivity)
infectivity <- infectivity / sum(infectivity)

width <- 7         #  => window (rolling mean one sided) in repronum() 
report.delay <- 7  #  => delay (reporting delay) in repronum() 
alpha <- 0.05      # => default conf.level in repronum() 

```


```{r shiny dygraph_plot Reproduction Number Rolling Mean}

shinyApp(
  
  ui = fluidPage(
    # Input: Select Country for plot ----
    titlePanel("Confirmed Cases with Reproduction Number"),
    selectInput(
      'country', label = 'Select Country:',
      choices = unique(corona_population$Country), selected = "Germany"),
    dygraphOutput("dygraph_plot_repro")
  ),
  
  server = function(input, output) {
    output$dygraph_plot_repro = renderDygraph({
      # input <- list()
      # input$country <- "Germany"
      
      
      data_repronum <- corona_abs_wide %>% 
        filter(Country == input$country) %>% 
        dplyr::select(Country, Date, Daily_Confirmed, Conf_rol_mean) %>% 
        ungroup() 
      
      # repronum_output <- repronum(new.cases = data_repronum$Daily_Conf_rol_mean, 
      repronum_output <- repronum(new.cases = data_repronum$Daily_Confirmed, 
                                  profile = infectivity, 
                                  window = width,
                                  delay = report.delay)
      
      
      data_repronum  <- bind_cols(data_repronum, repronum_output) %>% 
        rename(Repro_number = repronum)
      
      # change tibble in xts object
      index <- data_repronum$Date
      data_repronum  %<>% select(-Country, -Date, -repronum.se) 
      
      data_xts <- xts::xts(data_repronum, order.by = index)
      
      
      
      plot_dygraph_daily_repro(data_xts, input$country, last_date, weeks = weeks)
    })
  },
  
  options = list(height = 600)
)


```


```{r}

```

