---
title: Climate Config -
subtitle: Atmospheric $CO_2$ Concentration / Temperature / Precipitation
author: "Wolfgang Vollmer"
date: '`r Sys.Date()`'
output:
  pdf_document:
    fig_caption: no
    number_sections: yes
    toc: yes
    toc_depth: 3
  html_document: default
params:
  city: "Basel"
  temp_precip_both: "both"    

---

```{r setup internally only, eval = FALSE, echo = FALSE}
knitr::opts_chunk$set(eval = TRUE, echo = FALSE, warning = FALSE,      
                      message = FALSE, fig.width = 7, fig.asp = 0.618)
city <- params$city
temp_precip_selected <- params$temp_precip_both

```


```{r initialization, include = FALSE}
################################################################################
## Plot and Analyze                                                           ##
## Yearly/Monthly CO2 or Climate Temperature / Precipitation Data             ##
##                                                                            ##
##                                              Wolfgang Vollmer, March 2021  ##
##                                                                            ##
################################################################################

######  variables clean up, library() and	source() statements
# setwd("D:/Wolfgang/Programs-R/R-TimeSeriesAnalysis")
setwd(dirname(rstudioapi::getSourceEditorContext()$path))
# rm(list=ls()) # deletes all existing objects / variables !!
Prog.Start <- Sys.time()

suppressMessages(library(tidyverse))
suppressMessages(library(magrittr))
library(lubridate)
library(fpp3)  # tsibble, tsibbledata, fable, and feasts packages & some tidyverse
library(stlplus) # Enhanced Seasonal Decomposition of Time Series by Loess
library(DT)      # R interface to the JavaScript library DataTables
library(rlang)

library(checkmate)      # for assert functions

######  Plot and util functions
# source("./uts_climate.R")  # utility functions for time series
# source("./ggts_climate.R") # ggplot2 functions for time series plots
library(pkgTS)     # TimeSeries Functions - own R package on GitHub
                   # devtools::install_github("WoVollmer/pkgTS")

# for mean year values already NA values not stripped (na.rm = FALSE) 
# => for mean values over some years / periods stripping is not needed
# => valid for monthly and yearly data

```

```{r ggplot theme, include = FALSE}

theme_replace(
  plot.title = element_text(
    hjust = 0.5, face = "bold.italic", color = "darkcyan", size = 12),
  plot.subtitle = element_text(
    hjust = 0.5, face = "italic", color = "darkcyan")
)
x_axis_theme <- element_text(size = 14)

```

```{r settings, include = FALSE}

city_dwd <- c("Cottbus", "Giessen", "Hohenpeissenberg", "Mannheim", "Potsdam")
city_list <- c(city_dwd, "Basel", "Davos", "England", "Mauna Loa")

n_mismatches <- sum(ifelse(city %in% city_list, 0, 1))
if (n_mismatches > 0) { 
  stop(paste(paste(city, collapse = ", "), 
              "does not match to defined list of allowed cities:", 
              paste(city_list, collapse = ", ")))
}
if (length(city) > 1) { 
  stop(paste(paste(city, collapse = ", "), 
              "- support of more then one city entry not yet implemented")) 
}

# will be checked only if City != "Mauna Loa"
temp_precip_both <- c("Temperature", "temperature", 
                      "Precipitation", "precipitation",
                      "both", "Both")
measure <- str_to_title(match.arg(temp_precip_selected, temp_precip_both))

###### dafault settings
freq <- 12          # season lenght: year with 12 months

# key <- c("City", "Measure")   # all data have to have "City" & "Measure" column
key <- c("Measure") # w/o City reduces "strip" naming w/ facet_wrap/grid

y_label_measure <- c(Temperature = expression(paste("Temperature / ", degree*C)),
                     Precipitation = "Precipitation / mm/Month",
                     CO2 = expression(paste(CO[2], " Concentration / ppm")))

# kann be addressed after data reading with e.g.:
# y_label_measure["Temperature"]
# y_label_measure[unique(data_monthly_wide$Measure)]

# y_label_test <- c(Temperature = "Temperature degree*C",
#                      Precipitation = "Precipitation mm/",
#                   CO2 = "Mauna Loa")
# paste(y_label_test["Temperature"], y_label_test["CO2"], sep = " and ")
# paste(y_label_test, collapse = " and ")

```


```{r measure specific settings, eval = TRUE, include = FALSE}

span_m <- 7 * 12 # width of the rolling window in months

if (city == "Mauna Loa") {
  measure <- "CO2"
  span <- 7   # width of the rolling window in years, weather: => 30
  # for Times Series decompsition with stlplus()
  season_window <- 7     # odd, Temperature:  s.window=31, t.window=19
  trend_window  <- 41
  
  title_rmd <- paste(city, "- Atmospheric Carbon Dioxide Analysis")
  topic <- "Mauna Loa CO2 Concentrations"
  y_label <- expression(paste(CO[2], " Concentration / ppm"))
  y_label_text <- "CO2 Concentration / ppm"
  
} else {
  measure <- str_to_title(match.arg(temp_precip_selected, temp_precip_both))
  span <- 30  # width of the rolling window in years, CO2: => 6|7 years
  season_window <- 31  # odd, seasonal structure long running  # Precip to be checked
  trend_window <- 19   # to allow more rapid changes    
  
  if (measure == "Both") {
    measure <- "Temperature and Precipitation"
    y_label <- expression(paste("Precipitation / mm/Month    ", 
                                "   Temperature / ", degree*C))
    y_label_text <- "Temperature / degree C and Monthly Precipitation / mm"
  } else {
    if (measure == "Temperature") {
      y_label <- expression(paste("Temperature / ", degree*C))
      y_label_text <- "Temperature / degree C"
    } else {
      y_label <- "Monthly Precipitation / mm"
      y_label_text <- y_label
    }
    
  }
  title_rmd <- paste(city, "-", measure, "Climate Analysis")
  topic <- paste(city, "-", measure)
  
} 

```

```{r rds data reading}

f_name <- paste0( "./Data_rds_Temp_Precip_CO2/", city, "_wide.rds")
data_monthly_wide <- readRDS(f_name)

# if only Temperature or Precipitation analysis is requested
if (measure == "Temperature" | measure == "Precipitation") {
  data_monthly_wide <- data_monthly_wide %>% 
    dplyr::filter(Measure == measure)
}
measure_analysis <- as.character(unique(data_monthly_wide$Measure))
# measure <- paste(measure_analysis, collapse = " and ")
if (length(measure_analysis) == 0) { 
  stop(paste(paste("no", measure, "data exist for", city, "!")))
  }

fig_asp_mult <- case_when(length(measure_analysis) == 1 ~ 0.618,
          length(measure_analysis) == 2 ~ 1,
          length(measure_analysis) == 3 ~ 1.236)
```

```{r get yearly seasonaly data}

# filter within first year with Jan Temp and last year with Dec Temp
first_year <- data_monthly_wide %>% 
  filter(!is.na(Jan)) %$% 
  min(Year) 
last_year <- data_monthly_wide %>% 
  filter(!is.na(Dec)) %$% 
  max(Year)
data_monthly_wide <- data_monthly_wide %>% 
  filter(Year >= first_year & Year <= last_year)

# alternative: first_year <- data_monthly %$% year(min((Year_Month))) 
#              last_year <- data_monthly %$% year(max((Year_Month)))


data_monthly <- data_monthly_wide %>% 
  pivot_longer(cols = Jan:Dec,
               names_to = c("Month"),
               values_to = "count") %>% 
  unite(Year_Month, Year, Month, sep = "-", remove = FALSE) %>% 
  # => keep Year, Month column
  mutate(Year_Month = yearmonth(Year_Month)) %>% 
  as_tsibble(index = Year_Month, key = Measure) %>% 
  dplyr::select(City, Measure, Year_Month, Year, Month, count)

data_monthly$Month <- factor(data_monthly$Month, levels = month.abb)

# unique(key_data(data_monthly)[[1]]) # or better:
# unique(data_monthly$Measure)
# covered by measure_analysis


data_yearly <- uts_gen_yearly_seasonal_avg(data_monthly)
# no tsibble before first/ref/last_period calcualations
# data_yearly <- as_tsibble(data_yearly, index = Year, key = key)

```


```{r weather test data, eval = FALSE, echo = FALSE}

# for test purposes only - filter data from 1940 - 1954 and generate NA's
# with missing year 1949 and lot of NAs
weather_test_w_na <- FALSE  

if (weather_test_w_na) {
  test_monthly_wide <- filter(data_monthly_wide, Year >= 1940 & Year <= 1954 
                              & Year & Year != 1949)
  # note:   & Year & Year != 1949 not feasible, otherwise ts() indexing wrong
  #   running from 1940 - 1953 instead 1954 if 1949 is taken out
  test_monthly_wide[1, 9:11] <- NA
  test_monthly_wide[2, 6:7] <- NA
  test_monthly_wide[2, 12] <- NA
  
  data_monthly_wide <- test_monthly_wide
  
  data_monthly <- data_monthly_wide %>% 
    pivot_longer(cols = Jan:Dec,
                 names_to = c("Month"),
                 values_to = "count") %>% 
  dplyr::select(City, Measure, Year, Month, count)
}

```

```{r missing data, eval = TRUE}

# add colummns Raw (= orig counts + NAs), 
#     Interpolated (= orig and replaced NA values = count (updated))
#    &  NA_replace (= NAs and replaced NA values)
# for plots w/ & w/o replaced counts 
data_monthly <- data_monthly %>%  
  mutate(Raw = count,
       #  Interpolated = NA,
         NA_replace = NA)

## are there any NAs in data_monthly$count
n_row <- nrow(data_monthly)
n_na <- as_tibble(data_monthly) %>% 
  summarise(nr_na = sum(is.na(count))) %>% sum()
## => replace NA by interpolation separate for each time series
if (n_na != 0) {
  warning(paste(city, measure, "data file has missing values, #NA=",
                n_na, "out of", n_row))
  data_monthly_new <- tibble()   
  for (i in unique(key_data(data_monthly)[[1]])) {    
    # for (j in unique(key_data(data_monthly)[[2]])) {
    # data <- filter(data_monthly, City == i & Measure == j)
    data <- filter(data_monthly, Measure == i)
    data_interpolate <- as_tibble(uts_interpolate_na(data, freq))
    data_monthly_new <- bind_rows(data_interpolate, data_monthly_new)
  }
  #  NAs in column 'count' are now replaced by interpolated values !!
  #    previous NAs are in RAW (old count) and 
  #    replaced NAs are in updated count (only for easy check)
  # yearmonth() class is lost by bind_row
  
  data_monthly <- data_monthly_new %>% 
    mutate(Year_Month = yearmonth(Year_Month)) %>%  
    as_tsibble(index = Year_Month, key = key)
} 

data_monthly <- data_monthly %>%  group_by(City, Measure)
 
# saveRDS(data_monthly, paste0("./Data_rds_Temp_Precip_CO2/", city, 
#                              "_data_monthly_w_interpol.rds"))

# for TS_Forecast_CO2_Weather.Rmd - ETS / ARIMA models does not allow NAs
```


```{r}

```

