---
output:
  github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# Evaluations of Temperature, Precipitation and CO2 Times Series


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "##",
  fig.width = 8, 
  fig.height = 5.5,
  out.width = "90%"
)

```

The **Climate Visualization** rsp. **Forecast** RMD files provide climate time series analysis.
For **Mauna Loa** from *CO2* data, for **Basel / Davos / Cottbus/ Giessen/ Hohenpeissenberg/ Mannheim/ Potsdam** from *Temperature & Precipitation* data and for England of long-term *Temperature* data.

See provided PDF files.


## Data Sources 


### Temperatures and Precipitation

* Basel / Davos: **Federal Office of Meteorology and Climatology MeteoSwiss**

<https://www.meteoswiss.admin.ch/home/climate/swiss-climate-in-detail/homogeneous-data-series-since-1864.html>

* German Cities: **DWD Archiv Monats- und Tageswerte**

<https://www.dwd.de/DE/leistungen/klimadatendeutschland/klarchivtagmonat.html>  

(*Monatswerte historisch und aktuell*, 
column MO_TT (Temperature; Monatsmittel der Lufttemperatur in 2m Höhe in 
\textdegree C and	MO_RR (Precipitation; Monatssumme der Niederschlagshoehe in mm))

* England **Met Office - National Meteorological Service for the UK**

<https://www.metoffice.gov.uk/hadobs/hadcet/data/download.html>
Monthly_HadCET_mean.txt, 1659 to date


### CO2 Concentrations

**National Oceanic & Atmospheric Administration - Earth System Research Laboratory**

*NOAA ESRL *<https://www.esrl.noaa.gov/gmd/ccgg/trends/global.html>

Data file: Mauna Loa CO2 monthly mean data

<https://www.esrl.noaa.gov/gmd/ccgg/trends/data.html>

----------------------

Any remarks?    
Please let me know or provide some hints.
